// ISO 3166-1 alpha-2 country codes and names with emoji flags
export const countries = [
  { code: 'TR', name: 'Türkiye', flag: '🇹🇷' },
  { code: 'US', name: 'United States', flag: '🇺🇸' },
  { code: 'DE', name: 'Almanya', flag: '🇩🇪' },
  { code: 'FR', name: 'Fransa', flag: '🇫🇷' },
  { code: 'GB', name: 'İngiltere', flag: '🇬🇧' },
  { code: 'RU', name: 'Rusya', flag: '🇷🇺' },
  { code: 'IT', name: 'İtalya', flag: '🇮🇹' },
  { code: 'ES', name: 'İspanya', flag: '🇪🇸' },
  { code: 'JP', name: 'Japonya', flag: '🇯🇵' },
  { code: 'CN', name: 'Çin', flag: '🇨🇳' },
  { code: 'IN', name: 'Hindistan', flag: '🇮🇳' },
  { code: 'BR', name: 'Brezilya', flag: '🇧🇷' },
  { code: 'CA', name: 'Kanada', flag: '🇨🇦' },
  { code: 'NL', name: 'Hollanda', flag: '🇳🇱' },
  { code: 'SE', name: 'İsveç', flag: '🇸🇪' },
  { code: 'NO', name: 'Norveç', flag: '🇳🇴' },
  { code: 'FI', name: 'Finlandiya', flag: '🇫🇮' },
  { code: 'AZ', name: 'Azerbaycan', flag: '🇦🇿' },
  { code: 'KZ', name: 'Kazakistan', flag: '🇰🇿' },
  { code: 'UA', name: 'Ukrayna', flag: '🇺🇦' },
  { code: 'PL', name: 'Polonya', flag: '🇵🇱' },
  { code: 'GR', name: 'Yunanistan', flag: '🇬🇷' },
  { code: 'SA', name: 'Suudi Arabistan', flag: '🇸🇦' },
  { code: 'EG', name: 'Mısır', flag: '🇪🇬' },
  // ...daha fazla ülke eklenebilir
];
